#!/bin/sh

# turn capslock into left-control
xmodmap -e 'remove Lock = Caps_Lock'
xmodmap -e 'keysym Caps_Lock = Control_L'
xmodmap -e 'add Control = Control_L'

xscreensaver -no-splash &

spectrwm

mv $HOME/.xsession-errors $HOME/.xsession-errors.prev

