#!/bin/sh

# no fucking bells
xset b off

ssh-add </dev/null

# turn capslock into left-control
xmodmap -e 'remove Lock = Caps_Lock'
xmodmap -e 'keysym Caps_Lock = Control_L'
xmodmap -e 'add Control = Control_L'

# turn off the stupid middle-click-scroll thing
if command -V xinput; then
	xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Button Scrolling Button" 0
fi

# sync clipboards
if command -V autocutsel; then
	autocutsel -fork &
	autocutsel -selection PRIMARY -fork &
fi

xscreensaver -no-splash &

# redshift in SFO
if command -V redshift; then
	redshift -l 37.78:122.41 &
fi

spectrwm

mv $HOME/.xsession-errors $HOME/.xsession-errors.prev

